name: RSS Feed Updater

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 */2 * * *'  # 2시간마다 실행
  workflow_dispatch:       # 수동 실행 옵션

jobs:
  update-and-commit:
    runs-on: macos-latest
    
    steps:
    - name: 리포지토리 체크아웃
      uses: actions/checkout@v3

    - name: RSS 업데이트 실행
      run: swift run

    - name: README.md 업데이트 (XML 파일 목록)
      run: |
        echo "# RSS Feed List" > README.md
        echo "" >> README.md
        echo "이 저장소는 RSS 피드를 자동으로 업데이트하고 관리합니다." >> README.md
        echo "" >> README.md
        echo "## RSS Feeds" >> README.md
        echo "" >> README.md
        
        # Feeds 디렉터리에서 XML 파일 리스트업 (GitHub Pages URL)
        BASE_URL="https://inchan.github.io/RssFeeds"
        for file in Feeds/*.xml; do
          filename=$(basename "$file")
          echo "- [${filename}](${BASE_URL}/Feeds/${filename})" >> README.md
        done
        
        cat README.md

    - name: Deploy
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # publish 브랜치 체크아웃 (없으면 생성)
        if git show-ref --verify --quiet refs/heads/publish; then
          git checkout publish
        else
          git checkout --orphan publish
          git rm -rf .
        fi
        
        # Feeds 디렉터리 커밋
        git add Feeds/* README.md
        
        if [ -n "$(git diff --cached)" ]; then
          git commit -m "🤖 RSS Feed 업데이트 (자동 커밋)"
          git push --force origin publish  # 강제로 푸시
        else
          echo "변경 사항 없음"
        fi
