name: RSS Feed Updater

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 */2 * * *'  # 2시간마다 실행
  workflow_dispatch:       # 수동 실행 옵션

jobs:
  update-and-commit:
    runs-on: macos-latest
    
    steps:
    - name: 리포지토리 체크아웃
      uses: actions/checkout@v3

    - name: 최신 Swift 6 설치
      run: |
        brew install swift
        sudo xcode-select -switch /Applications/Xcode.app
        swift --version

    - name: RSS 업데이트 실행
      run: swift run

    - name: Deploy
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        git checkout publish || git checkout -b publish
        git merge main --no-commit --no-ff
        git add Feeds/*
        
        if [ -n "$(git diff --cached)" ]; then
          git commit -m "🤖 RSS Feed 업데이트 (자동 커밋)"
          git push origin publish
        else
          echo "변경 사항 없음"
        fi
